### ISSUE TITLE
Wrap lists

### ISSUE THREAD

**Issue by kpp** [RnDome/bwapi-c#19]
We need to implement:

- [x] Game_getStartLocations
- [x] Game_getNukeDots
- [x] Game_getEvents
- [x] Unit_getTrainingQueue

**Comment by nlinker** [comment]
I'll try to do this, agree?

**Comment by 0x7CFE** [comment]
Sure, carry on

**Comment by kpp** [comment]
@nlinker Have a look at #11 . This may help.
