### ISSUE TITLE
compile Dll.dll on Mac OS X

### ISSUE THREAD

**Issue by ttdonovan** [RnDome/bwapi-c#52]
I'm trying to build and compile bwapi-c on Mac OS X and ran into an issue with the `Dll.dll` module. This is the message I receive from `i686-w64-mingw32-gcc`. The gcc was installed from https://github.com/cosmo0920/homebrew-mingw_w64.

```
$ brew tap cosmo0920/mingw_w64
$ brew install-mingw-w64
$ brew install i686-w64-mingw32-gcc
```

 ```
$ i686-w64-mingw32-gcc -mabi=ms -shared -o Dll.dll Dll.c -I../include -L. -lBWAPIC
/var/folders/ww/mp9fm43j4017vxnz2cf_xw600000gn/T//ccBjd3YT.o:Dll.c:(.text+0xe1): undefined reference to `Game_setTextSize'
collect2: error: ld returned 1 exit status
```
Maybe all isn't necessary to use **bwapi-sys** and **bwapi-rs** - just trying to figure out how it all fits together.

**Comment by kpp** [comment]
Try to use source code for example from [release](https://github.com/RnDome/bwapi-c/archive/v0.3.0.tar.gz), not from master branch.

**Comment by dkashitsyn** [comment]
Hi @ttdonovan! Rust stuff isn't necessary for BWAPI-C. Latter may be used completely independent. 

Moreover, we're currently experiencing strange linker behavior when cross linking. Maybe your issue relates to that. From time to time I see errors with missing unwind symbols and for the moment I have no clue what causes them.

**Comment by ttdonovan** [comment]
@kpp Thanks using tag `v0.3.0` I was able to compile the dll.

**Comment by ttdonovan** [comment]
Sorry might have close prematurely - looks like a `bug` label was added for Version 0.4.0 milestone

**Comment by kpp** [comment]
It is a bug, actually. We have to push to develop and after a release we would merge develop into master so nobody ever will have such problem again.
